In [101]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [102]:
names=['sepal-length','sepal-width','petal-length','petal-width','class']

In [103]:
ds=pd.read_csv("Iris.csv",names=names)
print(ds.head())

   sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [104]:
X=ds.iloc[:,:-1]
y=ds.iloc[:,-1]
print(X.head())


   sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In [111]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3) 
KNN=KNeighborsClassifier(n_neighbors=7).fit(X_train,y_train)

In [112]:
y_pred=KNN.predict(X_test)

In [113]:
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor'],
      dtype=object)

In [114]:
i=0
print('%-25s %-25s %-25s'%('Original Label','Predicted Label','Correct/Wrong'))
print('\n')
for label in y_test:
    print('%-25s %-25s'%(label,y_pred[i]),end="")
    if(label==y_pred[i]):
        print('%-25s'%('Correct'))
    else:
        print('%-25s'%('Wrong'))
    i=i+1

Original Label            Predicted Label           Correct/Wrong            


Iris-versicolor           Iris-versicolor          Correct                  
Iris-virginica            Iris-virginica           Correct                  
Iris-virginica            Iris-virginica           Correct                  
Iris-virginica            Iris-versicolor          Wrong                    
Iris-versicolor           Iris-versicolor          Correct                  
Iris-setosa               Iris-setosa              Correct                  
Iris-setosa               Iris-setosa              Correct                  
Iris-versicolor           Iris-versicolor          Correct                  
Iris-setosa               Iris-setosa              Correct                  
Iris-virginica            Iris-virginica           Correct                  
Iris-setosa               Iris-setosa              Correct                  
Iris-virginica            Iris-virginica           Correct               

In [115]:
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))  
print("\n\nClassification Report:\n",metrics.classification_report(y_test, y_pred)) 
print('\nAccuracy of the classifer is %0.2f'%metrics.accuracy_score(y_test,y_pred))

Confusion Matrix:
 [[12  0  0]
 [ 0 18  0]
 [ 0  1 14]]


Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.95      1.00      0.97        18
 Iris-virginica       1.00      0.93      0.97        15

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45


Accuracy of the classifer is 0.98
